// AI mode copy. The model's own rules live in server/aiChat.ts.

export const aiMode = {
  toggleLabel: 'AI mode',
  toggleHint: 'Type your own question',
  onNote: 'AI mode · free-text answers are generated by the AI and checked against the same rules',
  placeholder: 'Ask a money question…',
  send: 'Send',
  thinking: 'Future You is thinking…',
  generatedTag: 'Generated',
  generatedNote: 'Generated by AI for this question. It has not been checked by a person, so open the source before you act on it.',
  unsourcedNote: "I couldn't match this to an official source, so treat it as unchecked. An adviser can confirm it.",
  personalNote: "Your figures stay with you: I haven't used them, and I'm not licensed to.",
  error: "I couldn't get an answer just now.",
  retry: 'Try again',
  switchToTopics: 'Use guided topics instead',
  limitNote: (max: number) => `Up to ${max} characters.`,
  privacyNote: "Don't type your name, account numbers or other details that identify you.",
};
